import { useCallback, useEffect, useRef, useState } from 'react'
import './App.css'
import {
  cancelBooking, createBooking, createCategory, createEvent, createPayment, deleteCategory, deleteEvent, fetchAdminReports,
  fetchAdminStatistics, fetchAdminUsers, fetchAttendees, fetchBooking, fetchBookings, fetchCategories, fetchEvent, fetchEvents,
  fetchOrganizerAnalytics, fetchOrganizerEvents, fetchTicket, fetchUserBookings, loginUser, registerUser, searchAdminUsers, updateAdminUser, updateEvent,
} from './api'

const fallbackImage = 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=80'
const blankEvent = { title: '', description: '', category: 'Technology', location: '', organizer: '', imageUrl: '', price: 'Free', seatsLeft: 50, maxTicketsPerBooking: 10, startDate: '', startTime: '18:00', status: 'DRAFT' }
const blankAttendee = { fullName: '', email: '', phone: '', gender: '', age: '', address: '', city: '', state: '', pinCode: '' }

function App() {
  const [events, setEvents] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState(''); const [authMode, setAuthMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '', phone: '', remember: true })
  const [authOpen, setAuthOpen] = useState(false); const [authTarget, setAuthTarget] = useState('/')
  const [session, setSession] = useState(readStoredSession); const [search, setSearch] = useState(''); const [bookings, setBookings] = useState([])
  const [path, setPath] = useState(window.location.pathname); const [authLoading, setAuthLoading] = useState(false)
  const go = (to) => { window.history.pushState({}, '', to); setPath(to); window.scrollTo(0, 0) }
  const route = parseRoute(path)
  const loadCatalog = () => Promise.all([fetchEvents(), fetchCategories()]).then(([eventData, categoryData]) => { setEvents(eventData); setCategories(categoryData); setLoading(false) }).catch(() => { setMessage('Unable to reach the API right now.'); setLoading(false) })
  useEffect(() => { loadCatalog(); const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  useEffect(() => { if (session?.role === 'USER') fetchBookings(session.token).then(setBookings).catch((error) => setMessage(error.message)) }, [session])
  const signOut = () => { localStorage.removeItem('eventsphere-session'); setSession(null); setBookings([]); go('/'); setMessage('Signed out.') }
  const openAuth = useCallback((target = path, mode = 'login') => { setAuthTarget(target); setAuthMode(mode); setAuthOpen(true) }, [path])
  const handleSubmit = async (event) => {
    event.preventDefault(); if (authLoading) return; setAuthLoading(true)
    try {
      const result = normalizeSession(authMode === 'login' ? await loginUser(form.email, form.password) : await registerUser(form))
      if (form.remember) localStorage.setItem('eventsphere-session', JSON.stringify(result)); else localStorage.removeItem('eventsphere-session')
      setSession(result); setAuthOpen(false); go(dashboardPath(result.role, authTarget)); setMessage(authMode === 'login' ? 'Login successful.' : 'Registration successful.')
    } catch (error) { setMessage(error.message || 'Validation error. Please check your details.') } finally { setAuthLoading(false) }
  }
  if (route.name === 'dashboard' && session?.role === 'ORGANIZER') return <OrganizerDashboard session={session} categories={categories} go={go} signOut={signOut} onExit={() => go('/')} />
  if (route.name === 'dashboard' && session?.role === 'ADMIN') return <AdminDashboard session={session} categories={categories} setCategories={setCategories} go={go} signOut={signOut} onExit={() => go('/')} />
  return <div className="app-shell"><Header session={session} go={go} openAuth={openAuth} signOut={signOut} path={path}/><main>
    {(route.name === 'home' || route.name === 'events') && <HomePage events={events} categories={categories} loading={loading} search={search} setSearch={setSearch} go={go} session={session} bookings={bookings} setBookings={setBookings} refresh={loadCatalog} setMessage={setMessage} />}
    {route.name === 'dashboard' && session?.role === 'USER' && <HomePage events={events} categories={categories} loading={loading} search={search} setSearch={setSearch} go={go} session={session} bookings={bookings} setBookings={setBookings} refresh={loadCatalog} setMessage={setMessage} />}
    {route.name === 'dashboard' && !session && <RequireLogin go={go} setMessage={setMessage} />}
    {route.name === 'event' && <EventDetails eventId={route.id} go={go} session={session} openAuth={openAuth} />}
    {route.name === 'booking' && <BookingPage eventId={route.id} session={session} go={go} setMessage={setMessage} openAuth={openAuth} />}
    {route.name === 'payment' && <PaymentPage bookingId={route.id} session={session} go={go} setMessage={setMessage} openAuth={openAuth} />}
    {route.name === 'success' && <BookingSuccess bookingId={route.id} session={session} go={go} />}
    {route.name === 'myBookings' && <MyBookings session={session} go={go} setMessage={setMessage} setAppBookings={setBookings} />}
    {route.name === 'account' && <AccountPage session={session} bookings={bookings} go={go} setMessage={setMessage} />}
    {route.name === 'settings' && <SettingsPage session={session} go={go} setMessage={setMessage} />}
    {route.name === 'ticket' && <TicketPage bookingId={route.id} session={session} go={go} />}
    {(authOpen || route.name === 'auth') && <AuthModal mode={authMode} setMode={setAuthMode} form={form} setForm={setForm} onSubmit={handleSubmit} onClose={() => { setAuthOpen(false); if (route.name === 'auth') go('/') }} setMessage={setMessage} loading={authLoading}/>}
    {message && <Toast message={message} onClose={() => setMessage('')} />}
  </main></div>
}

function Header({ session, go, openAuth, signOut, path }) {
  return <header className="topbar"><button className="brand link-button" onClick={() => go('/')}>EventSphere</button><nav className="nav-links"><button onClick={() => go('/')}>Home</button><button onClick={() => go('/events')}>Events</button><button onClick={() => session ? go('/my-bookings') : openAuth('/my-bookings')}>My Bookings</button>{session && session.role !== 'USER' && <button onClick={() => go('/dashboard')}>Dashboard</button>}</nav><div className="topbar-actions">{session ? <ProfileMenu session={session} go={go} signOut={signOut} /> : <><button className="outline-btn" onClick={() => openAuth(path, 'login')}>Sign In</button><button className="primary-btn" onClick={() => openAuth(path, 'register')}>Sign Up</button></>}</div></header>
}

function ProfileMenu({ session, go, signOut }) {
  const [open, setOpen] = useState(false); const menuRef = useRef(null)
  const name = session?.name?.trim() || 'Account'; const image = session?.profileImage || session?.profilePicture || session?.avatarUrl || session?.imageUrl
  const initials = name === 'Account' ? 'A' : name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()
  const navigate = (target) => { setOpen(false); go(target) }; const logout = () => { setOpen(false); signOut() }
  useEffect(() => { if (!open) return undefined; const down = (event) => { if (menuRef.current && !menuRef.current.contains(event.target)) setOpen(false) }; const key = (event) => { if (event.key === 'Escape') setOpen(false) }; document.addEventListener('pointerdown', down); document.addEventListener('keydown', key); return () => { document.removeEventListener('pointerdown', down); document.removeEventListener('keydown', key) } }, [open])
  return <div className="profile-menu" ref={menuRef}><button className="profile-trigger" type="button" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen((value) => !value)}>{image ? <img className="profile-avatar" src={image} alt="" onError={imageFallback} /> : <span className="profile-avatar">{initials}</span>}<span className="profile-name">{name}</span><span className="profile-arrow" aria-hidden="true">v</span></button>{open && <div className="profile-dropdown" role="menu"><button type="button" role="menuitem" onClick={() => navigate('/account')}><span aria-hidden="true">ID</span>My Account</button><button type="button" role="menuitem" onClick={() => navigate('/my-bookings')}><span aria-hidden="true">TK</span>My Bookings</button><button type="button" role="menuitem" onClick={() => navigate('/settings')}><span aria-hidden="true">ST</span>Settings</button><div className="profile-divider" /><button type="button" role="menuitem" onClick={logout}><span aria-hidden="true">OUT</span>Logout</button></div>}</div>
}

function parseRoute(path) {
  const parts = path.split('/').filter(Boolean); if (!parts.length) return { name: 'home' }
  if (parts[0] === 'events' && parts[1]) return { name: 'event', id: parts[1] }; if (parts[0] === 'events') return { name: 'events' }
  if (parts[0] === 'booking' && parts[1]) return { name: 'booking', id: parts[1] }; if (parts[0] === 'payment' && parts[1]) return { name: 'payment', id: parts[1] }
  if (parts[0] === 'booking-success' && parts[1]) return { name: 'success', id: parts[1] }; if (parts[0] === 'my-bookings') return { name: 'myBookings' }
  if (parts[0] === 'account') return { name: 'account' }; if (parts[0] === 'settings') return { name: 'settings' }
  if (parts[0] === 'ticket' && parts[1]) return { name: 'ticket', id: parts[1] }; if (parts[0] === 'auth') return { name: 'auth' }; if (parts[0] === 'dashboard') return { name: 'dashboard' }
  return { name: 'home' }
}

function AuthModal({ mode, setMode, form, setForm, onSubmit, onClose, setMessage, loading }) {
  const [showPassword, setShowPassword] = useState(false)
  const emailInvalid = form.email && !/^\S+@\S+\.\S+$/.test(form.email)
  const passwordInvalid = form.password && form.password.length < 8
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Authentication"><section className="auth-modal-pro"><div className="auth-side"><p className="eyebrow">EventSphere</p><h2>{mode === 'login' ? 'Welcome back.' : 'Join EventSphere.'}</h2><p>Discover events, manage tickets, and keep every booking in one polished account dashboard.</p><div className="auth-metrics"><span>Live events</span><strong>Curated for every city</strong></div></div><form onSubmit={onSubmit} className="auth-form auth-panel"><div className="section-heading"><div><p className="eyebrow">Account</p><h2>{mode === 'login' ? 'Sign In' : 'Register'}</h2></div><button className="ghost-btn" type="button" onClick={onClose}>Close</button></div><div className="segmented"><button type="button" className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Login</button><button type="button" className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>Register</button></div>{mode === 'register' && <><label>Full name<input required placeholder="Aarav Sharma" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label>Phone<input placeholder="10-digit mobile number" pattern="[0-9]{10}" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })}/></label></>}<label>Email<input required type="email" placeholder="you@example.com" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/>{emailInvalid && <small className="field-error">Enter a valid email address.</small>}</label><label>Password<div className="password-field"><input required minLength="8" type={showPassword ? 'text' : 'password'} placeholder="At least 8 characters" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })}/><button type="button" className="outline-btn" onClick={() => setShowPassword((value) => !value)}>{showPassword ? 'Hide' : 'Show'}</button></div>{passwordInvalid && <small className="field-error">Password must be at least 8 characters.</small>}</label><div className="auth-options"><label className="checkbox-row"><input type="checkbox" checked={form.remember} onChange={(event) => setForm({ ...form, remember: event.target.checked })}/> Remember me</label><button type="button" className="link-button" onClick={() => setMessage('Password reset UI placeholder. Please contact support for now.')}>Forgot Password?</button></div><button className="primary-btn loading-btn" disabled={loading}>{loading && <span className="spinner" />}{mode === 'login' ? 'Sign In' : 'Sign Up'}</button></form></section></div>
}

function HomePage({ events, categories, loading, search, setSearch, go, session, bookings, setBookings, refresh, setMessage }) {
  const visibleEvents = events.filter((event) => `${event.title} ${event.category} ${event.location} ${event.organizer}`.toLowerCase().includes(search.toLowerCase()))
  const upcoming = [...events].filter((event) => !event.startDate || event.startDate >= todayIso()).slice(0, 6)
  const trending = [...events].sort((a, b) => Number(a.seatsLeft ?? 999) - Number(b.seatsLeft ?? 999)).slice(0, 3)
  const featured = visibleEvents.slice(0, 6)
  return <><section className="hero-card"><div className="hero-copy"><p className="eyebrow">EventSphere</p><h1>Find your next unforgettable experience.</h1><p className="hero-text">Browse events, reserve tickets, and manage every booking from one responsive dashboard.</p><div className="hero-actions"><input className="search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, category, location, organizer" /></div></div><div className="hero-panel"><div className="hero-stat"><strong>{events.length}</strong><span>Events available</span></div><div className="hero-stat"><strong>{categories.length}</strong><span>Popular categories</span></div></div></section><EventSection title="Featured Events" eyebrow="Curated picks" events={featured} loading={loading} go={go}/><EventSection title="Trending Events" eyebrow="Selling fast" events={trending} loading={loading} go={go}/><section className="section-block"><div className="section-heading"><div><p className="eyebrow">Popular categories</p><h2>Explore events</h2></div><button className="outline-btn" onClick={() => setSearch('')}>All Events</button></div><div className="chip-row">{categories.map((category) => <button className="chip" key={category.id} onClick={() => setSearch(category.name)}>{category.name}</button>)}</div><div className="card-grid">{loading ? <SkeletonCards /> : visibleEvents.map((event) => <EventCard key={event.id} event={event} go={go} />)}{!loading && !visibleEvents.length && <EmptyState title="No events found" text="Try another city, category, or organizer." />}</div></section><EventSection title="Upcoming Events" eyebrow="Plan ahead" events={upcoming} loading={loading} go={go}/><HomeExtras go={go} setSearch={setSearch} />{session?.role === 'USER' && <Bookings bookings={bookings} token={session.token} setBookings={setBookings} refresh={refresh} setMessage={setMessage} />}</>
}

function EventSection({ title, eyebrow, events, loading, go }) {
  return <section className="section-block"><div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div><div className="card-grid">{loading ? <SkeletonCards /> : events.map((event) => <EventCard key={`${title}-${event.id}`} event={event} go={go}/>)}</div></section>
}

function EventCard({ event, go }) {
  const seats = Number(event.seatsLeft ?? 0)
  return <article className="event-card"><div className="image-wrap"><img src={event.imageUrl || fallbackImage} alt={event.title || 'Event'} onError={imageFallback}/><span className="badge category-badge">{event.category || 'Event'}</span><span className="badge price-badge">{event.price || 'Free'}</span></div><div className="event-body"><div className="event-meta">{formatDate(event.startDate)} at {event.startTime || 'TBA'}</div><h3>{event.title}</h3><p>{event.location} - {event.organizer}</p><div className="seat-meter"><span>{seats > 0 ? `${seats} seats left` : 'Sold out'}</span><div><i style={{ width: `${Math.max(8, Math.min(100, seats))}%` }} /></div></div><div className="button-row"><button className="primary-btn" onClick={() => go(`/events/${event.id}`)}>View Details</button><button className="outline-btn" onClick={() => go(`/booking/${event.id}`)} disabled={seats < 1}>Book</button></div></div></article>
}

function EventDetails({ eventId, go, session, openAuth }) {
  const { data: event, loading, error } = useLoad(() => fetchEvent(eventId), [eventId])
  if (loading) return <PageChrome go={go} title="Event Details"><SkeletonDetail /></PageChrome>; if (error) return <p className="status-message">{error}</p>
  const unavailable = !event.seatsLeft || (event.startDate && event.startTime && new Date(`${event.startDate}T${event.startTime}`) <= new Date())
  return <PageChrome go={go} title={event.title}><section className="section-block auth-card detail-layout"><img className="detail-banner" src={event.imageUrl || fallbackImage} alt={event.title} onError={imageFallback}/><div><p className="eyebrow">{event.category}</p><h2>{event.title}</h2><p>{event.description}</p><div className="info-grid"><Info label="Date & Time" value={`${formatDate(event.startDate)} at ${event.startTime}`} /><Info label="Venue" value={event.location} /><Info label="Organizer" value={event.organizer} /><Info label="Price" value={event.price} /><Info label="Available seats" value={`${event.seatsLeft} seats`} /><Info label="Booking limit" value={`${event.maxTicketsPerBooking || 10} tickets`} /></div><button className="primary-btn" disabled={unavailable} onClick={() => session ? go(`/booking/${event.id}`) : openAuth(`/booking/${event.id}`)}>{unavailable ? 'Unavailable' : 'Book Now'}</button></div></section></PageChrome>
}

function BookingPage({ eventId, session, go, setMessage, openAuth }) {
  const { data: event, loading, error } = useLoad(() => fetchEvent(eventId), [eventId]); const [quantity, setQuantity] = useState(1); const [attendee, setAttendee] = useState(blankAttendee); const [attendees, setAttendees] = useState([{ ...blankAttendee }]); const [processing, setProcessing] = useState(false)
  const unit = event ? priceNumber(event.price) : 0; const total = unit * quantity
  useEffect(() => { if (!session) { setMessage('Please sign in to book tickets.'); openAuth(`/booking/${eventId}`) } }, [session, eventId, openAuth, setMessage])
  if (!session) return null; if (loading) return <PageChrome go={go} title="Booking"><SkeletonDetail /></PageChrome>; if (error) return <p className="status-message">{error}</p>
  const update = (name, value) => setAttendee({ ...attendee, [name]: value }); const max = Math.min(event.seatsLeft, event.maxTicketsPerBooking || 10); const eventStarted = event.startDate && event.startTime && new Date(`${event.startDate}T${event.startTime}`) <= new Date()
  const setTicketAttendee = (index, field, value) => setAttendees((items) => items.map((item, i) => i === index ? { ...item, [field]: value } : item))
  const decrement = () => { setQuantity(Math.max(1, quantity - 1)); setAttendees((items) => items.slice(0, Math.max(1, quantity - 1))) }
  const increment = () => { if (quantity >= max) return setMessage(`Maximum ${event.maxTicketsPerBooking || 10} tickets allowed.`); setQuantity(quantity + 1); setAttendees((items) => [...items, { ...blankAttendee }]) }
  const copyPurchaser = (index, checked) => checked && setAttendees((items) => items.map((item, i) => i === index ? { ...item, fullName: attendee.fullName, email: attendee.email, phone: attendee.phone } : item))
  const submit = async (e) => { e.preventDefault(); if (processing) return; if (eventStarted) return setMessage('This event has already started.'); if (max < 1) return setMessage('This event is sold out.'); if (quantity > max) return setMessage(`Maximum ${event.maxTicketsPerBooking || 10} tickets allowed.`); if (!/^\d{10}$/.test(attendee.phone)) return setMessage('Enter a valid 10-digit purchaser phone number.'); if (attendees.some((item) => !item.fullName.trim() || !/^\S+@\S+\.\S+$/.test(item.email) || !/^\d{10}$/.test(item.phone))) return setMessage('Enter a valid name, email, and 10-digit phone for every attendee.'); setProcessing(true); try { const booking = await createBooking(session.token, { eventId: event.id, quantity, ...attendee, age: Number(attendee.age), attendees: attendees.map((item) => ({ ...item, gender: item.gender || attendee.gender, age: Number(item.age || attendee.age), address: item.address || attendee.address, city: item.city || attendee.city, state: item.state || attendee.state, pinCode: item.pinCode || attendee.pinCode })) }); setMessage('Booking successful. Complete payment to confirm your ticket.'); go(`/payment/${booking.id}`) } catch (err) { setMessage(err.message) } finally { setProcessing(false) } }
  return <PageChrome go={go} title="Book Tickets"><section className="section-block auth-card"><div className="section-heading"><div><p className="eyebrow">Booking</p><h2>{event.title}</h2></div><strong>{formatMoney(total)}</strong></div><div className="booking-summary"><img src={event.imageUrl || fallbackImage} alt={event.title} onError={imageFallback}/><div><p>{formatDate(event.startDate)} at {event.startTime}</p><p>{event.location}</p><p>Ticket price: {event.price}</p><div className="quantity-row"><button type="button" className="outline-btn" onClick={decrement}>-</button><strong>{quantity}</strong><button type="button" className="outline-btn" disabled={quantity >= max || max < 1 || eventStarted} onClick={increment}>+</button></div><small>{max < 1 ? 'Sold out' : `Maximum ${event.maxTicketsPerBooking || 10} tickets per booking. ${event.seatsLeft} seat(s) remaining.`}</small></div></div><form className="auth-form form-grid" onSubmit={submit}><h3 className="form-heading">Purchaser details</h3>{['fullName','email','phone','gender','age','address','city','state','pinCode'].map((field) => <input key={field} required type={field === 'email' ? 'email' : field === 'age' ? 'number' : 'text'} placeholder={label(field)} value={attendee[field]} onChange={(e) => update(field, e.target.value)} />)}<div className="attendee-list">{attendees.map((person, index) => <fieldset key={index}><legend>Attendee {index + 1}</legend><label className="checkbox-row"><input type="checkbox" onChange={(e) => copyPurchaser(index, e.target.checked)}/> Same as purchaser</label><input required placeholder="Full name" value={person.fullName} onChange={(e) => setTicketAttendee(index, 'fullName', e.target.value)}/><input required type="email" placeholder="Email" value={person.email} onChange={(e) => setTicketAttendee(index, 'email', e.target.value)}/><input required placeholder="10-digit phone" value={person.phone} onChange={(e) => setTicketAttendee(index, 'phone', e.target.value)}/></fieldset>)}</div><button className="primary-btn loading-btn" disabled={processing || max < 1 || eventStarted}>{processing && <span className="spinner" />}{processing ? 'Creating booking...' : 'Continue to Payment'}</button></form></section></PageChrome>
}

function PaymentPage({ bookingId, session, go, setMessage, openAuth }) {
  const { data: booking, loading, error, setData } = useLoad(() => session ? fetchBooking(session.token, bookingId) : Promise.reject(new Error('Please sign in to continue.')), [bookingId, session]); const [method, setMethod] = useState(''); const [processing, setProcessing] = useState(false)
  useEffect(() => { if (!session) openAuth(`/payment/${bookingId}`) }, [session, bookingId, openAuth])
  if (!session) return null; if (loading) return <p className="status-message">Loading payment...</p>; if (error) return <p className="status-message">{error}</p>
  const amount = Number(booking.ticketAmount ?? priceNumber(booking.eventPrice) * booking.quantity); const fee = amount > 0 ? 49 : 0; const gst = Number((fee * .18).toFixed(2)); const grand = booking.grandTotal ?? amount + fee + gst
  const pay = async () => { if (!method) return setMessage('Select a payment option.'); if (processing || booking.paymentStatus === 'SUCCESS') return; setProcessing(true); try { const result = await createPayment(session.token, booking.id, method); setData(result); setMessage('Payment completed.'); go(`/booking-success/${booking.id}`) } catch (err) { setMessage(err.message) } finally { setProcessing(false) } }
  return <PageChrome go={go} title="Payment"><section className="section-block auth-card"><p className="eyebrow">Payment</p><h2>{booking.eventTitle}</h2><div className="info-grid"><Info label="Quantity" value={booking.quantity} /><Info label="Ticket amount" value={formatMoney(amount)} /><Info label="Convenience fee" value={formatMoney(fee)} /><Info label="GST" value={formatMoney(gst)} /><Info label="Grand Total" value={formatMoney(grand)} /></div><div className="chip-row">{['UPI','Credit Card','Debit Card','Net Banking'].map((option) => <button type="button" key={option} className={method === option ? 'primary-btn' : 'chip'} onClick={() => setMethod(option)}>{option}</button>)}</div><button className="primary-btn loading-btn" disabled={processing || booking.paymentStatus === 'SUCCESS'} onClick={pay}>{processing && <span className="spinner" />}{processing ? 'Processing payment...' : booking.paymentStatus === 'SUCCESS' ? 'Paid' : 'Pay Securely'}</button></section></PageChrome>
}

function BookingSuccess({ bookingId, session, go }) {
  const { data: booking, loading, error } = useLoad(() => session ? fetchBooking(session.token, bookingId) : Promise.reject(new Error('Please sign in to continue.')), [bookingId, session])
  if (!session) return null; if (loading) return <p className="status-message">Loading confirmation...</p>; if (error) return <p className="status-message">{error}</p>
  return <PageChrome go={go} title="Booking Confirmed"><section className="section-block auth-card"><p className="eyebrow">Success</p><h2>Booking confirmed successfully.</h2><div className="info-grid"><Info label="Booking ID" value={booking.id} /><Info label="Ticket Number" value={booking.ticketNumber} /><Info label="Event Name" value={booking.eventTitle} /><Info label="Date" value={formatDate(booking.startDate)} /><Info label="Venue" value={booking.venue} /><Info label="Attendee Name" value={booking.attendeeName} /><Info label="Total Paid" value={formatMoney(booking.grandTotal || 0)} /></div><div className="dashboard-tabs"><button className="primary-btn" onClick={() => go(`/ticket/${booking.id}`)}>Download Ticket</button><button className="outline-btn" onClick={() => go('/my-bookings')}>My Bookings</button><button className="outline-btn" onClick={() => go('/')}>Home</button></div></section></PageChrome>
}

function MyBookings({ session, go, setMessage, setAppBookings }) {
  const { data: bookings = [], loading, error, setData } = useLoad(() => session ? fetchUserBookings(session.token) : Promise.reject(new Error('Please sign in to continue.')), [session])
  if (!session) return <RequireLogin go={go} setMessage={setMessage} />; if (loading) return <PageChrome go={go} title="My Bookings"><SkeletonCards /></PageChrome>; if (error) return <p className="status-message">{error}</p>
  const upcoming = bookings.filter((booking) => booking.startDate >= todayIso() && booking.status !== 'CANCELLED'); const previous = bookings.filter((booking) => !upcoming.includes(booking))
  const handleCancel = async (id) => { try { const current = bookings.find((booking) => booking.id === id); const updated = mergeCancelledBooking(current, await cancelBooking(session.token, id)); setData((items) => items.map((booking) => booking.id === id ? updated : booking)); setAppBookings?.((items) => items.map((booking) => booking.id === id ? mergeCancelledBooking(booking, updated) : booking)); setMessage('Booking cancelled. Status updated immediately.') } catch (e) { setMessage(e.message) } }
  return <PageChrome go={go} title="My Bookings"><section className="section-block"><div className="section-heading"><div><p className="eyebrow">Ticket history</p><h2>Booking History</h2></div><button className="outline-btn" onClick={() => go('/')}>Home</button></div><AccountSummary session={session} bookings={bookings} go={go}/><h3>Upcoming bookings</h3><BookingCards bookings={upcoming} go={go} onCancel={handleCancel} empty="No upcoming bookings."/><h3>Previous bookings</h3><BookingCards bookings={previous} go={go} onCancel={handleCancel} empty="No previous bookings."/></section></PageChrome>
}

function BookingCards({ bookings, go, onCancel, empty }) {
  const canCancel = (booking) => booking.status !== 'CANCELLED' && booking.startDate >= todayIso()
  if (!bookings.length) return <EmptyState title={empty} text="When you book an event, tickets and QR details will appear here." />
  return <div className="booking-grid">{bookings.map((booking) => <article className={`booking-card ${booking.status === 'CANCELLED' ? 'is-cancelled' : ''}`} key={booking.id}><img src={booking.eventImageUrl || fallbackImage} alt={booking.eventTitle} onError={imageFallback}/><div className="booking-card-body"><div className="section-heading compact"><div><p className="eyebrow">Booking #{booking.id}</p><h3>{booking.eventTitle}</h3></div><img className="mini-qr" src={localQr(booking.ticketNumber || booking.confirmationCode || booking.id)} alt="QR code"/></div><p>{booking.venue}</p><div className="booking-facts"><Info label="Date" value={formatDate(booking.startDate)} /><Info label="Time" value={booking.startTime} /><Info label="Tickets" value={booking.quantity} /><Info label="Booking ID" value={booking.confirmationCode || booking.id} /></div><div className="badge-row"><StatusBadge value={booking.status} type="booking"/><StatusBadge value={booking.paymentStatus} type="payment"/></div><div className="button-row"><button className="primary-btn" onClick={() => go(`/ticket/${booking.id}`)}>View Ticket</button><button className="danger-btn" disabled={!canCancel(booking)} onClick={() => onCancel(booking.id)}>{booking.status === 'CANCELLED' ? 'Cancelled' : 'Cancel'}</button><button className="outline-btn" onClick={() => go(`/ticket/${booking.id}`)}>Download Ticket</button><button className="outline-btn" onClick={() => go('/')}>Home</button></div></div></article>)}</div>
}

function AccountPage({ session, bookings, go, setMessage }) {
  if (!session) return <RequireLogin go={go} setMessage={setMessage} />
  const stats = bookingStats(bookings)
  return <PageChrome go={go} title="My Account"><section className="account-hero"><div className="account-avatar">{session.name ? session.name[0].toUpperCase() : 'A'}</div><div><p className="eyebrow">Account dashboard</p><h2>{session.name || 'EventSphere Member'}</h2><p>{session.email}</p></div></section><section className="auth-card"><div className="info-grid"><Info label="Name" value={session.name} /><Info label="Email" value={session.email} /><Info label="Phone" value={session.phone} /><Info label="Role" value={session.role} /><Info label="Member Since" value={session.memberSince || 'Recently joined'} /></div></section><section className="stats-grid account-stats"><div className="hero-stat"><strong>{stats.upcoming}</strong><span>Upcoming Events</span></div><div className="hero-stat"><strong>{stats.completed}</strong><span>Completed Events</span></div><div className="hero-stat"><strong>{stats.cancelled}</strong><span>Cancelled Events</span></div><div className="hero-stat"><strong>{stats.tickets}</strong><span>Total Tickets</span></div></section><section className="auth-card"><h3>Quick Actions</h3><div className="dashboard-tabs"><button className="primary-btn" onClick={() => setMessage('Edit profile UI placeholder.')}>Edit Profile</button><button className="outline-btn" onClick={() => go('/my-bookings')}>My Bookings</button><button className="outline-btn" onClick={() => go('/settings')}>Settings</button><button className="outline-btn" onClick={() => go('/')}>Home</button></div></section></PageChrome>
}

function SettingsPage({ session, go, setMessage }) {
  if (!session) return <RequireLogin go={go} setMessage={setMessage} />
  return <PageChrome go={go} title="Settings"><section className="auth-card"><p className="eyebrow">Preferences</p><h2>Settings</h2><div className="info-grid"><Info label="Email notifications" value="Enabled" /><Info label="SMS updates" value="Enabled" /><Info label="Payment reminders" value="Enabled" /><Info label="Privacy" value="Standard" /></div><div className="button-row"><button className="outline-btn" onClick={() => go('/account')}>Back to Account</button><button className="outline-btn" onClick={() => go('/')}>Home</button></div></section></PageChrome>
}

function TicketPage({ bookingId, session, go }) {
  const { data: ticket, loading, error } = useLoad(() => session ? fetchTicket(session.token, bookingId) : Promise.reject(new Error('Please sign in to continue.')), [bookingId, session])
  if (!session) return null; if (loading) return <p className="status-message">Loading ticket...</p>; if (error) return <p className="status-message">{error}</p>
  const qr = localQr(ticket.ticketNumber)
  return <PageChrome go={go} title="Ticket"><section className="section-block auth-card ticket-wrap"><div className="section-heading no-print"><div><p className="eyebrow">Booking details</p><h2>{ticket.eventTitle}</h2></div><div className="toggle-row"><button className="primary-btn" onClick={() => window.print()}>Download Ticket</button><button className="outline-btn" onClick={() => go('/my-bookings')}>My Bookings</button><button className="outline-btn" onClick={() => go('/')}>Home</button></div></div><div className="ticket-card"><img className="qr-code" src={qr} alt="Ticket QR code"/><div><p className="eyebrow">EventSphere Ticket</p><h2>{ticket.eventTitle}</h2><div className="info-grid"><Info label="Booking ID" value={ticket.id} /><Info label="Ticket Number" value={ticket.ticketNumber} /><Info label="Date & Time" value={`${formatDate(ticket.startDate)} at ${ticket.startTime}`} /><Info label="Venue" value={ticket.venue} /><Info label="Booking status" value={<StatusBadge value={ticket.status} type="booking"/>} /><Info label="Payment" value={<StatusBadge value={ticket.paymentStatus} type="payment"/>} /><Info label="Total paid" value={formatMoney(ticket.grandTotal)} /></div><h3>Attendees</h3>{ticket.attendees?.map((attendee) => <p key={attendee.id}>{attendee.ticketNumber}: {attendee.fullName} - {attendee.email} - {attendee.phone}</p>)}</div></div></section></PageChrome>
}

function RequireLogin({ go, setMessage }) { useEffect(() => { setMessage('Please sign in to continue.'); go('/auth') }, [go, setMessage]); return null }
// eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect
function useLoad(loader, deps) { const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { let active = true; setLoading(true); loader().then((value) => { if (active) { setData(value); setError('') } }).catch((err) => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false } }, deps); return { data, loading, error, setData } }
function Info({ label, value }) { return <div className="info-item"><span>{label}</span><strong>{value || 'Not available'}</strong></div> }
function PageChrome({ go, title, children }) { return <><div className="breadcrumbs"><button onClick={() => go('/')}>Home</button><span>/</span><span>{title}</span><button className="outline-btn" onClick={() => window.history.length > 1 ? window.history.back() : go('/')}>Back</button></div>{children}</> }
function Toast({ message, onClose }) { useEffect(() => { const id = setTimeout(onClose, 3500); return () => clearTimeout(id) }, [onClose]); const tone = /failed|error|invalid|unable|required/i.test(message) ? 'error' : 'success'; return <div className={`toast ${tone}`}><span>{message}</span><button onClick={onClose}>Close</button></div> }
function StatusBadge({ value, type }) { const labelText = statusLabel(value); return <span className={`status-badge ${type}-${statusKey(value)}`}>{labelText}</span> }
function EmptyState({ title, text }) { return <div className="empty-state"><div className="empty-art">ES</div><h3>{title}</h3><p>{text}</p></div> }
function SkeletonCards() { return Array.from({ length: 3 }, (_, index) => <div className="skeleton-card" key={index}><span /><strong /><p /></div>) }
function SkeletonDetail() { return <div className="skeleton-detail"><span /><div><strong /><p /><p /></div></div> }
function AccountSummary({ session, bookings, go }) { return <section className="auth-card profile-card"><h3>Profile information</h3><div className="info-grid"><Info label="Name" value={session.name} /><Info label="Email" value={session.email} /><Info label="Role" value={session.role} /><Info label="Total bookings" value={bookings.length} /></div><button className="outline-btn" onClick={() => go('/account')}>Open Account Dashboard</button></section> }
function label(value) { return value.replace(/([A-Z])/g, ' $1').replace(/^./, (char) => char.toUpperCase()).replace('Pin', 'PIN') }
function statusKey(value) { return String(value || 'PENDING').trim().replace(/^BOOKING_/i, '').replace(/^PAYMENT_/i, '').replace(/[\s_]+/g, '-').toLowerCase() }
function statusLabel(value) { return String(value || 'PENDING').trim().replace(/^BOOKING_/i, '').replace(/^PAYMENT_/i, '').replace(/[_-]+/g, ' ').toUpperCase() }
function priceNumber(value) { const digits = String(value || '').replace(/[^0-9.]/g, ''); return digits ? Number(digits) : 0 }
function formatMoney(value) { return `Rs ${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}` }
function formatDate(value) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Date TBA' }
function todayIso() { return new Date().toISOString().slice(0, 10) }
function imageFallback(event) { event.currentTarget.onerror = null; event.currentTarget.src = fallbackImage }
function readStoredSession() { try { const session = normalizeSession(JSON.parse(localStorage.getItem('eventsphere-session') || 'null')); if (!session?.token) localStorage.removeItem('eventsphere-session'); return session?.token ? session : null } catch { localStorage.removeItem('eventsphere-session'); return null } }
function normalizeRole(value) { return String(value || 'USER').trim().replace(/^ROLE_/i, '').toUpperCase() }
function normalizeSession(value) { if (!value) return null; return { ...value, token: value.token || value.accessToken || value.jwt, role: normalizeRole(value.role || value.user?.role), email: value.email || value.user?.email || '', name: value.name || value.user?.name || '', phone: value.phone || value.user?.phone || '' } }
function dashboardPath(role, userTarget = '/') { return normalizeRole(role) === 'ADMIN' || normalizeRole(role) === 'ORGANIZER' ? '/dashboard' : userTarget }
function mergeCancelledBooking(current = {}, updated = {}) { const paid = String(updated.paymentStatus || current.paymentStatus || '').toUpperCase() === 'SUCCESS'; return { ...current, ...updated, status: 'CANCELLED', paymentStatus: updated.paymentStatus || (paid ? 'REFUNDED' : current.paymentStatus || 'CANCELLED') } }
function bookingStats(bookings) { const today = todayIso(); return bookings.reduce((stats, booking) => ({ upcoming: stats.upcoming + (booking.startDate >= today && booking.status !== 'CANCELLED' ? 1 : 0), completed: stats.completed + (booking.status === 'COMPLETED' || (booking.startDate < today && booking.status !== 'CANCELLED') ? 1 : 0), cancelled: stats.cancelled + (booking.status === 'CANCELLED' ? 1 : 0), tickets: stats.tickets + Number(booking.quantity || 0) }), { upcoming: 0, completed: 0, cancelled: 0, tickets: 0 }) }
function localQr(value) {
  const text = String(value || 'EventSphere'); let hash = 0
  for (let index = 0; index < text.length; index += 1) hash = ((hash << 5) - hash + text.charCodeAt(index)) | 0
  const cells = Array.from({ length: 21 }, (_, y) => Array.from({ length: 21 }, (_, x) => {
    const marker = (x < 7 && y < 7) || (x > 13 && y < 7) || (x < 7 && y > 13)
    return marker || Math.abs(Math.sin((x + 1) * (y + 1) * (hash || 7))) > .48
  }))
  const rects = cells.flatMap((row, y) => row.map((on, x) => on ? `<rect x="${x * 8}" y="${y * 8}" width="8" height="8"/>` : '')).join('')
  return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="168" height="168" viewBox="0 0 168 168"><rect width="168" height="168" fill="white"/><g fill="#111827">${rects}</g></svg>`)}`
}

function Bookings({ bookings, token, setBookings, refresh, setMessage }) { return <section className="section-block auth-card"><p className="eyebrow">User dashboard</p><h2>Recent booking history</h2>{bookings.length ? bookings.slice(0, 3).map((booking) => <div className="booking-item" key={booking.id}><span>{booking.confirmationCode || `Booking #${booking.id}`} - {booking.quantity} ticket(s)</span><StatusBadge value={booking.status} type="booking"/>{booking.status !== 'CANCELLED' && <button className="outline-btn" onClick={async () => { try { const updated = mergeCancelledBooking(booking, await cancelBooking(token, booking.id)); setBookings((items) => items.map((item) => item.id === booking.id ? updated : item)); refresh(); setMessage('Booking cancelled. Status updated immediately.'); } catch (error) { setMessage(error.message) } }}>Cancel</button>}</div>) : <EmptyState title="No bookings yet" text="Your recent tickets will appear here." />}</section> }

function OrganizerDashboard({ session, categories, go, signOut, onExit }) {
  const [tab, setTab] = useState('overview'); const [events, setEvents] = useState([]); const [analytics, setAnalytics] = useState(null); const [editing, setEditing] = useState(null); const [attendees, setAttendees] = useState([]); const [message, setMessage] = useState('')
  const load = useCallback(() => Promise.all([fetchOrganizerEvents(session.token), fetchOrganizerAnalytics(session.token)]).then(([myEvents, stats]) => { setEvents(myEvents); setAnalytics(stats) }).catch((e) => setMessage(e.message)), [session.token]);
  useEffect(() => { load() }, [load])
  const save = async (event, values) => { event.preventDefault(); const data = { ...values, seatsLeft: Number(values.seatsLeft) }; try { if (data.id) await updateEvent(session.token, data.id, data); else await createEvent(session.token, data); setEditing(null); load(); setMessage('Event saved.'); } catch (e) { setMessage(e.message) } }
  return <DashboardShell title="Organizer Dashboard" tab={tab} setTab={setTab} tabs={['overview', 'events', 'create', 'attendees', 'reports']} session={session} go={go} signOut={signOut} onExit={onExit}>{message && <p className="status-message">{message}</p>}{tab === 'overview' && <Stats stats={analytics} labels={{ events: 'My events', published: 'Published', registrations: 'Registrations', remainingSeats: 'Seats remaining' }}/>} {tab === 'events' && <EventManager events={events} onEdit={(event) => { setEditing(event); setTab('create') }} onDelete={async (id) => { await deleteEvent(session.token, id); load() }}/>} {tab === 'create' && <EventForm key={editing?.id || 'new'} event={editing || blankEvent} categories={categories} onSave={save} onCancel={() => { setEditing(null); setTab('events') }}/>} {tab === 'attendees' && <AttendeeManager events={events} token={session.token} attendees={attendees} setAttendees={setAttendees}/>} {tab === 'reports' && <section className="auth-card"><h2>Organizer report</h2><p>Download-ready summary: {analytics?.registrations || 0} confirmed registrations across {analytics?.events || 0} events.</p></section>}</DashboardShell>
}

function AdminDashboard({ session, categories, setCategories, go, signOut, onExit }) {
  const [tab, setTab] = useState('overview'); const [users, setUsers] = useState([]); const [stats, setStats] = useState(null); const [reports, setReports] = useState(null); const [events, setEvents] = useState([]); const [newCategory, setNewCategory] = useState(''); const [message, setMessage] = useState('')
  const load = useCallback(() => Promise.all([fetchAdminUsers(session.token), fetchAdminStatistics(session.token), fetchAdminReports(session.token), fetchEvents()]).then(([u,s,r,e]) => { setUsers(u); setStats(s); setReports(r); setEvents(e) }).catch((e) => setMessage(e.message)), [session.token]);
  useEffect(() => { load() }, [load])
  return <DashboardShell title="Admin Dashboard" tab={tab} setTab={setTab} tabs={['overview', 'users', 'organizers', 'events', 'categories', 'reports']} session={session} go={go} signOut={signOut} onExit={onExit}>{message && <p className="status-message">{message}</p>}{tab === 'overview' && <Stats stats={stats} labels={{ users: 'Users', organizers: 'Organizers', events: 'Events', bookings: 'Bookings', availableSeats: 'Open seats' }}/>} {(tab === 'users' || tab === 'organizers') && <UserManager users={users.filter((user) => tab === 'users' || user.role === 'ORGANIZER')} token={session.token} onChange={load}/>} {tab === 'events' && <EventManager events={events} onDelete={async (id) => { await deleteEvent(session.token, id); load() }}/>} {tab === 'categories' && <section className="auth-card"><h2>Manage categories</h2><form className="inline-form" onSubmit={async (e) => { e.preventDefault(); try { const category = await createCategory(session.token, newCategory); setCategories((items) => [...items, category]); setNewCategory(''); } catch (error) { setMessage(error.message) } }}><input value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder="Category name" required/><button className="primary-btn">Add</button></form>{categories.map((category) => <div className="booking-item" key={category.id}><span>{category.name}</span><button className="outline-btn" onClick={async () => { await deleteCategory(session.token, category.id); setCategories((items) => items.filter((item) => item.id !== category.id)) }}>Delete</button></div>)}</section>} {tab === 'reports' && <section className="auth-card"><h2>Platform reports</h2><p>{reports?.events?.length || 0} events - {reports?.recentBookings?.length || 0} recent bookings</p>{reports?.recentBookings?.map((booking) => <div className="booking-item" key={booking.id}><span>{booking.confirmationCode} - {booking.status} - {booking.quantity} ticket(s)</span></div>)}</section>}</DashboardShell>
}

function DashboardShell({ title, tabs, tab, setTab, session, go, signOut, onExit, children }) { return <div className="app-shell"><header className="topbar"><strong className="brand">{title}</strong><nav className="nav-links"><button onClick={onExit}>Home</button><button onClick={() => go('/events')}>Events</button></nav><div className="topbar-actions">{session && <ProfileMenu session={session} go={go} signOut={signOut} />}</div></header><main><div className="dashboard-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'primary-btn' : 'outline-btn'} onClick={() => setTab(item)}>{label(item)}</button>)}</div>{children}</main></div> }
function Stats({ stats, labels }) { return <section className="stats-grid">{stats && Object.entries(labels).map(([key, itemLabel]) => <div className="hero-stat" key={key}><strong>{stats[key] ?? 0}</strong><span>{itemLabel}</span></div>)}</section> }
function EventManager({ events, onEdit, onDelete }) { return <section className="auth-card"><h2>Manage events</h2>{events.map((event) => <div className="booking-item" key={event.id}><span>{event.title} - {event.status} - {event.seatsLeft} seats</span><div>{onEdit && <button className="outline-btn" onClick={() => onEdit(event)}>Edit</button>} <button className="danger-btn" onClick={() => onDelete(event.id)}>Delete</button></div></div>)}{!events.length && <EmptyState title="No events yet" text="Create an event to start selling tickets." />}</section> }
function EventForm({ event, categories, onSave, onCancel }) { const [data, setData] = useState(event); const field = (name, type = 'text') => <input required={name !== 'imageUrl'} type={type} value={data[name] ?? ''} onChange={(e) => setData({ ...data, [name]: e.target.value })} placeholder={name}/>; return <section className="auth-card"><h2>{data.id ? 'Edit event' : 'Create event'}</h2><form className="auth-form" onSubmit={(e) => onSave(e, { ...data, seatsLeft: Number(data.seatsLeft), maxTicketsPerBooking: Number(data.maxTicketsPerBooking || 1) })}>{field('title')}<textarea required value={data.description} onChange={(e) => setData({ ...data, description: e.target.value })} placeholder="Description"/>{field('organizer')}<select value={data.category} onChange={(e) => setData({ ...data, category: e.target.value })}>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select>{field('location')}{field('startDate', 'date')}{field('startTime', 'time')}{field('price')}{field('seatsLeft', 'number')}{field('maxTicketsPerBooking', 'number')}{field('imageUrl')}<select value={data.status} onChange={(e) => setData({ ...data, status: e.target.value })}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select><button className="primary-btn">Save event</button><button type="button" className="outline-btn" onClick={onCancel}>Cancel</button></form></section> }
function AttendeeManager({ events, token, attendees, setAttendees }) { const [selected, setSelected] = useState(null); return <section className="auth-card"><h2>Attendee list</h2><select value={selected || ''} onChange={async (e) => { const id = e.target.value; setSelected(id); setAttendees(id ? await fetchAttendees(token, id) : []) }}><option value="">Select an event</option>{events.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select>{attendees.map((entry) => <div className="booking-item" key={entry.booking.id}><span>{entry.eventTitle} - Booking #{entry.booking.id} - {entry.booking.quantity} ticket(s) - {entry.booking.status}</span><div>{entry.attendees?.map((person) => <p key={person.id}>{person.ticketNumber}: {person.fullName} - {person.email} - {person.phone}</p>) || <p>{entry.attendee?.name || entry.booking.userEmail}</p>}</div></div>)}</section> }
function UserManager({ users, token, onChange }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [searching, setSearching] = useState(false); const [error, setError] = useState('')
  const runSearch = async (event) => { event?.preventDefault(); setSearching(true); try { setResults(await searchAdminUsers(token, query)); setError('') } catch (e) { setError(e.message) } finally { setSearching(false) } }
  return <section className="auth-card"><h2>Manage accounts</h2><form className="inline-form" onSubmit={runSearch}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name, email, phone, or user ID"/><button className="primary-btn" disabled={searching}>{searching ? 'Searching...' : 'Search Users'}</button></form>{error && <p className="status-message">{error}</p>}{results.map((entry) => <article className="user-search-card" key={entry.profile.id}><div className="section-heading"><div><h3>{entry.profile.name || 'Unnamed user'}</h3><p>{entry.profile.email} - {entry.profile.phone || 'No phone'} - User #{entry.profile.id}</p></div><strong>{formatMoney(entry.totalSpent)}</strong></div><div className="info-grid"><Info label="Active bookings" value={entry.activeBookings} /><Info label="Cancelled bookings" value={entry.cancelledBookings} /><Info label="Total spent" value={formatMoney(entry.totalSpent)} /><Info label="Role" value={entry.profile.role} /></div>{entry.bookingHistory.length ? entry.bookingHistory.map((booking) => <div className="booking-item" key={booking.id}><span>#{booking.id} - {booking.eventTitle} - {booking.quantity} ticket(s) - {booking.status}</span><span>{booking.paymentStatus}</span></div>) : <p className="empty-state">No bookings for this user.</p>}</article>)}{users.map((user) => <div className="booking-item" key={user.id}><span>{user.name} - {user.email} - {user.role} - {user.enabled ? 'Active' : 'Disabled'}</span><div><select value={user.role} onChange={async (e) => { await updateAdminUser(token, user.id, { role: e.target.value }); onChange() }}><option>USER</option><option>ORGANIZER</option><option>ADMIN</option></select><button className="outline-btn" onClick={async () => { await updateAdminUser(token, user.id, { enabled: !user.enabled }); onChange() }}>{user.enabled ? 'Disable' : 'Enable'}</button></div></div>)}</section>
}
function HomeExtras({ go, setSearch }) {
  const cityClick = (city) => { setSearch(city); go('/events') }
  return <><section className="discovery-section" aria-labelledby="cities-heading"><div className="section-heading"><div><p className="eyebrow">Cities</p><h2 id="cities-heading">Experiences near you</h2></div></div><div className="city-grid">{['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad', 'Pune', 'Chennai'].map((city) => <button className="city-card" key={city} onClick={() => cityClick(city)}>{city}<span>Explore events</span></button>)}</div></section><section className="discovery-section split-section"><div><p className="eyebrow">About</p><h2>From plans to packed houses.</h2><p>Discover inspiring local experiences, reserve your spot in seconds, and keep every ticket in one place.</p></div><div className="trust-grid"><button type="button" onClick={() => window.location.href = 'mailto:support@eventsphere.local'}><strong>Contact</strong><span>support@eventsphere.local</span></button><button type="button" onClick={() => go('/settings')}><strong>Privacy Policy</strong><span>Transparent booking data use.</span></button><button type="button" onClick={() => go('/settings')}><strong>Terms</strong><span>Clear event and ticket rules.</span></button></div></section><footer className="footer"><button type="button" onClick={() => go('/')}><strong>EventSphere</strong></button><button type="button" onClick={() => go('/')}>About</button><button type="button" onClick={() => window.location.href = 'mailto:support@eventsphere.local'}>Contact</button><button type="button" onClick={() => go('/settings')}>Privacy Policy</button><button type="button" onClick={() => go('/settings')}>Terms</button><button type="button" onClick={() => go('/events')}>Events</button></footer></>
}

export default App
