import { useEffect, useState } from 'react'
import './App.css'
import {
  cancelBooking, createBooking, createCategory, createEvent, createPayment, deleteCategory, deleteEvent, fetchAdminReports,
  fetchAdminStatistics, fetchAdminUsers, fetchAttendees, fetchBooking, fetchBookings, fetchCategories, fetchEvent, fetchEvents,
  fetchOrganizerAnalytics, fetchOrganizerEvents, fetchTicket, fetchUserBookings, loginUser, registerUser, updateAdminUser, updateEvent,
} from './api'

const fallbackImage = 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80'
const blankEvent = { title: '', description: '', category: 'Technology', location: '', organizer: '', imageUrl: '', price: 'Free', seatsLeft: 50, startDate: '', startTime: '18:00', status: 'DRAFT' }
const blankAttendee = { fullName: '', email: '', phone: '', gender: '', age: '', address: '', city: '', state: '', pinCode: '' }

function App() {
  const [events, setEvents] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState(''); const [authMode, setAuthMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '', phone: '' })
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('eventsphere-session') || 'null')); const [search, setSearch] = useState(''); const [bookings, setBookings] = useState([])
  const [path, setPath] = useState(window.location.pathname)
  const go = (to) => { window.history.pushState({}, '', to); setPath(to); window.scrollTo(0, 0) }
  const route = parseRoute(path)
  const loadCatalog = () => Promise.all([fetchEvents(), fetchCategories()]).then(([eventData, categoryData]) => { setEvents(eventData); setCategories(categoryData); setLoading(false) }).catch(() => { setMessage('Unable to reach the API right now.'); setLoading(false) })
  useEffect(() => { loadCatalog(); const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  useEffect(() => { if (session?.role === 'USER') fetchBookings(session.token).then(setBookings).catch((error) => setMessage(error.message)) }, [session])
  const signOut = () => { localStorage.removeItem('eventsphere-session'); setSession(null); setBookings([]); go('/'); setMessage('Signed out.') }
  const handleSubmit = async (event) => { event.preventDefault(); try { const result = authMode === 'login' ? await loginUser(form.email, form.password) : await registerUser(form); localStorage.setItem('eventsphere-session', JSON.stringify(result)); setSession(result); go(result.role === 'USER' ? '/' : '/dashboard'); setMessage('Signed in successfully.'); } catch (error) { setMessage(error.message) } }
  if (session?.role === 'ORGANIZER' && route.name === 'dashboard') return <OrganizerDashboard session={session} categories={categories} onExit={() => go('/')} />
  if (session?.role === 'ADMIN' && route.name === 'dashboard') return <AdminDashboard session={session} categories={categories} setCategories={setCategories} onExit={() => go('/')} />
  return <div className="app-shell"><header className="topbar"><button className="brand link-button" onClick={() => go('/')}>EventSphere</button><nav className="nav-links"><button onClick={() => go('/events')}>Events</button><button onClick={() => session ? go('/my-bookings') : go('/auth')}>{session?.role === 'USER' ? 'My Bookings' : session ? 'Account' : 'Login'}</button>{session && session.role !== 'USER' && <button onClick={() => go('/dashboard')}>Dashboard</button>}</nav><div className="topbar-actions">{session ? <button className="ghost-btn" onClick={signOut}>Logout</button> : <button className="primary-btn" onClick={() => { setAuthMode('register'); go('/auth') }}>Register</button>}</div></header><main>
    {(route.name === 'home' || route.name === 'events') && <HomePage events={events} categories={categories} loading={loading} search={search} setSearch={setSearch} go={go} session={session} bookings={bookings} setBookings={setBookings} refresh={loadCatalog} setMessage={setMessage} />}
    {route.name === 'event' && <EventDetails eventId={route.id} go={go} />}
    {route.name === 'booking' && <BookingPage eventId={route.id} session={session} go={go} setMessage={setMessage} />}
    {route.name === 'payment' && <PaymentPage bookingId={route.id} session={session} go={go} setMessage={setMessage} />}
    {route.name === 'success' && <BookingSuccess bookingId={route.id} session={session} go={go} />}
    {route.name === 'myBookings' && <MyBookings session={session} go={go} setMessage={setMessage} />}
    {route.name === 'ticket' && <TicketPage bookingId={route.id} session={session} go={go} />}
    {route.name === 'auth' && <section className="section-block auth-card"><div className="section-heading"><div><p className="eyebrow">Account</p><h2>{authMode === 'login' ? 'Login to EventSphere' : 'Create your account'}</h2></div><div className="toggle-row"><button className="ghost-btn" onClick={() => setAuthMode('login')}>Login</button><button className="primary-btn" onClick={() => setAuthMode('register')}>Register</button></div></div><form onSubmit={handleSubmit} className="auth-form">{authMode === 'register' && <><input required placeholder="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/><input placeholder="Phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })}/></>}<input required type="email" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/><input required minLength="8" type="password" placeholder="Password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })}/><button className="primary-btn">{authMode === 'login' ? 'Sign in' : 'Create account'}</button></form></section>}
    {message && <p className="status-message">{message}</p>}
  </main></div>
}

function parseRoute(path) {
  const parts = path.split('/').filter(Boolean); if (!parts.length) return { name: 'home' }
  if (parts[0] === 'events' && parts[1]) return { name: 'event', id: parts[1] }; if (parts[0] === 'events') return { name: 'events' }
  if (parts[0] === 'booking' && parts[1]) return { name: 'booking', id: parts[1] }; if (parts[0] === 'payment' && parts[1]) return { name: 'payment', id: parts[1] }
  if (parts[0] === 'booking-success' && parts[1]) return { name: 'success', id: parts[1] }; if (parts[0] === 'my-bookings') return { name: 'myBookings' }
  if (parts[0] === 'ticket' && parts[1]) return { name: 'ticket', id: parts[1] }; if (parts[0] === 'auth') return { name: 'auth' }; if (parts[0] === 'dashboard') return { name: 'dashboard' }
  return { name: 'home' }
}

function HomePage({ events, categories, loading, search, setSearch, go, session, bookings, setBookings, refresh, setMessage }) {
  const visibleEvents = events.filter((event) => `${event.title} ${event.category} ${event.location} ${event.organizer}`.toLowerCase().includes(search.toLowerCase()))
  return <><section className="hero-card"><div className="hero-copy"><p className="eyebrow">Discover and manage events</p><h1>Find your next unforgettable experience.</h1><p className="hero-text">Browse events, reserve tickets, and manage every stage of your event.</p><div className="hero-actions"><input className="search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, category, location, organizer" /></div></div><div className="hero-panel"><div className="hero-stat"><strong>{events.length}</strong><span>Events available</span></div><div className="hero-stat"><strong>{categories.length}</strong><span>Categories</span></div></div></section>
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Browse by category</p><h2>Explore events</h2></div></div><div className="chip-row">{categories.map((category) => <button className="chip" key={category.id} onClick={() => setSearch(category.name)}>{category.name}</button>)}<button className="chip" onClick={() => setSearch('')}>All</button></div><div className="card-grid">{loading ? <p>Loading events...</p> : visibleEvents.map((event) => <EventCard key={event.id} event={event} go={go} />)}</div></section>
    <HomeExtras />{session?.role === 'USER' && <Bookings bookings={bookings} token={session.token} setBookings={setBookings} refresh={refresh} setMessage={setMessage} />}</>
}

function EventCard({ event, go }) { return <article className="event-card"><img src={event.imageUrl || fallbackImage} alt=""/><div className="event-body"><div className="event-meta">{event.category} - {event.startDate}</div><h3>{event.title}</h3><p>{event.location} - {event.organizer}</p><div className="event-footer"><span>{event.price}</span><span>{event.seatsLeft} left</span></div><button className="primary-btn" onClick={() => go(`/events/${event.id}`)}>View details</button></div></article> }

function EventDetails({ eventId, go }) {
  const { data: event, loading, error } = useLoad(() => fetchEvent(eventId), [eventId])
  if (loading) return <p className="status-message">Loading event details...</p>; if (error) return <p className="status-message">{error}</p>
  return <section className="section-block auth-card detail-layout"><img className="detail-banner" src={event.imageUrl || fallbackImage} alt=""/><div><p className="eyebrow">{event.category}</p><h2>{event.title}</h2><p>{event.description}</p><div className="info-grid"><Info label="Date & Time" value={`${event.startDate} at ${event.startTime}`} /><Info label="Venue" value={event.location} /><Info label="City & State" value={event.location} /><Info label="Organizer" value={event.organizer} /><Info label="Price" value={event.price} /><Info label="Available seats" value={`${event.seatsLeft} seats`} /></div><button className="primary-btn" disabled={!event.seatsLeft} onClick={() => go(`/booking/${event.id}`)}>Book Now</button></div></section>
}

function BookingPage({ eventId, session, go, setMessage }) {
  const { data: event, loading, error } = useLoad(() => fetchEvent(eventId), [eventId]); const [quantity, setQuantity] = useState(1); const [attendee, setAttendee] = useState(blankAttendee)
  const unit = event ? priceNumber(event.price) : 0; const total = unit * quantity
  useEffect(() => { if (!session) { setMessage('Please sign in to book tickets.'); go('/auth') } }, [session, go, setMessage])
  if (!session) return null; if (loading) return <p className="status-message">Loading booking form...</p>; if (error) return <p className="status-message">{error}</p>
  const update = (name, value) => setAttendee({ ...attendee, [name]: value })
  const submit = async (e) => { e.preventDefault(); if (!/^\d{10}$/.test(attendee.phone)) return setMessage('Enter a valid 10-digit phone number.'); if (quantity > event.seatsLeft) return setMessage('Quantity cannot exceed available seats.'); try { const booking = await createBooking(session.token, { eventId: event.id, quantity, ...attendee, age: Number(attendee.age) }); setMessage('Booking created. Complete payment to confirm your ticket.'); go(`/payment/${booking.id}`) } catch (err) { setMessage(err.message) } }
  return <section className="section-block auth-card"><div className="section-heading"><div><p className="eyebrow">Booking</p><h2>{event.title}</h2></div><strong>{formatMoney(total)}</strong></div><div className="booking-summary"><img src={event.imageUrl || fallbackImage} alt=""/><div><p>{event.startDate} at {event.startTime}</p><p>{event.location}</p><p>Ticket price: {event.price}</p><div className="quantity-row"><button className="ghost-btn" onClick={() => setQuantity(Math.max(1, quantity - 1))}>-</button><strong>{quantity}</strong><button className="ghost-btn" onClick={() => setQuantity(Math.min(event.seatsLeft, quantity + 1))}>+</button></div></div></div><form className="auth-form form-grid" onSubmit={submit}>{['fullName','email','phone','gender','age','address','city','state','pinCode'].map((field) => <input key={field} required type={field === 'email' ? 'email' : field === 'age' ? 'number' : 'text'} placeholder={label(field)} value={attendee[field]} onChange={(e) => update(field, e.target.value)} />)}<button className="primary-btn">Continue to Payment</button></form></section>
}

function PaymentPage({ bookingId, session, go, setMessage }) {
  const { data: booking, loading, error, setData } = useLoad(() => session ? fetchBooking(session.token, bookingId) : Promise.reject(new Error('Please sign in to continue.')), [bookingId, session]); const [method, setMethod] = useState('')
  if (!session) return <RequireLogin go={go} setMessage={setMessage} />; if (loading) return <p className="status-message">Loading payment...</p>; if (error) return <p className="status-message">{error}</p>
  const amount = booking.ticketAmount ?? priceNumber(booking.eventPrice) * booking.quantity; const fee = amount > 0 ? 49 : 0; const gst = Number((fee * .18).toFixed(2)); const grand = amount + fee + gst
  const pay = async () => { if (!method) return setMessage('Select a payment option.'); try { const result = await createPayment(session.token, booking.id, method); setData(result); setMessage('Payment successful.'); go(`/booking-success/${booking.id}`) } catch (err) { setMessage(err.message) } }
  return <section className="section-block auth-card"><p className="eyebrow">Payment</p><h2>{booking.eventTitle}</h2><div className="info-grid"><Info label="Quantity" value={booking.quantity} /><Info label="Ticket amount" value={formatMoney(amount)} /><Info label="Convenience fee" value={formatMoney(fee)} /><Info label="GST" value={formatMoney(gst)} /><Info label="Grand Total" value={formatMoney(grand)} /></div><div className="chip-row">{['UPI','Credit Card','Debit Card','Net Banking'].map((option) => <button type="button" key={option} className={method === option ? 'primary-btn' : 'chip'} onClick={() => setMethod(option)}>{option}</button>)}</div><button className="primary-btn" onClick={pay}>Pay Securely</button></section>
}

function BookingSuccess({ bookingId, session, go }) {
  const { data: booking, loading, error } = useLoad(() => session ? fetchBooking(session.token, bookingId) : Promise.reject(new Error('Please sign in to continue.')), [bookingId, session])
  if (!session) return null; if (loading) return <p className="status-message">Loading confirmation...</p>; if (error) return <p className="status-message">{error}</p>
  return <section className="section-block auth-card"><p className="eyebrow">Success</p><h2>Booking confirmed successfully.</h2><div className="info-grid"><Info label="Booking ID" value={booking.id} /><Info label="Ticket Number" value={booking.ticketNumber} /><Info label="Event Name" value={booking.eventTitle} /><Info label="Date" value={booking.startDate} /><Info label="Venue" value={booking.venue} /><Info label="Attendee Name" value={booking.attendeeName} /><Info label="Total Paid" value={formatMoney(booking.grandTotal || 0)} /></div><div className="dashboard-tabs"><button className="primary-btn" onClick={() => go(`/ticket/${booking.id}`)}>Download Ticket</button><button className="ghost-btn" onClick={() => go('/my-bookings')}>View My Bookings</button><button className="ghost-btn" onClick={() => go('/')}>Back to Home</button></div></section>
}

function MyBookings({ session, go, setMessage }) {
  const { data: bookings = [], loading, error } = useLoad(() => session ? fetchUserBookings(session.token) : Promise.reject(new Error('Please sign in to continue.')), [session])
  if (!session) return <RequireLogin go={go} setMessage={setMessage} />; if (loading) return <p className="status-message">Loading bookings...</p>; if (error) return <p className="status-message">{error}</p>
  return <section className="section-block"><div className="section-heading"><div><p className="eyebrow">User dashboard</p><h2>My Bookings</h2></div></div><div className="card-grid">{bookings.map((booking) => <article className="event-card" key={booking.id}><img src={booking.eventImageUrl || fallbackImage} alt=""/><div className="event-body"><div className="event-meta">{booking.startDate} - {booking.status}</div><h3>{booking.eventTitle}</h3><p>{booking.venue}</p><div className="event-footer"><span>{booking.quantity} ticket(s)</span><span>{booking.paymentStatus}</span></div><button className="primary-btn" onClick={() => go(`/ticket/${booking.id}`)}>View Ticket</button></div></article>)}</div>{!bookings.length && <p>No bookings yet.</p>}</section>
}

function TicketPage({ bookingId, session, go }) {
  const { data: ticket, loading, error } = useLoad(() => session ? fetchTicket(session.token, bookingId) : Promise.reject(new Error('Please sign in to continue.')), [bookingId, session])
  if (!session) return null; if (loading) return <p className="status-message">Loading ticket...</p>; if (error) return <p className="status-message">{error}</p>
  const qr = localQr(ticket.ticketNumber)
  return <section className="section-block auth-card ticket-wrap"><div className="section-heading no-print"><div><p className="eyebrow">Ticket</p><h2>{ticket.eventTitle}</h2></div><div className="toggle-row"><button className="primary-btn" onClick={() => window.print()}>Download Ticket</button><button className="ghost-btn" onClick={() => go('/my-bookings')}>My Bookings</button></div></div><div className="ticket-card"><img className="qr-code" src={qr} alt="Ticket QR code"/><div><p className="eyebrow">EventSphere Ticket</p><h2>{ticket.eventTitle}</h2><div className="info-grid"><Info label="Booking ID" value={ticket.id} /><Info label="Ticket Number" value={ticket.ticketNumber} /><Info label="Attendee Name" value={ticket.attendeeName} /><Info label="Date & Time" value={`${ticket.startDate} at ${ticket.startTime}`} /><Info label="Venue" value={ticket.venue} /><Info label="Organizer" value={ticket.organizer} /></div></div></div></section>
}

function RequireLogin({ go, setMessage }) { useEffect(() => { setMessage('Please sign in to continue.'); go('/auth') }, [go, setMessage]); return null }
function useLoad(loader, deps) { const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { let active = true; setLoading(true); loader().then((value) => { if (active) { setData(value); setError('') } }).catch((err) => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false } }, deps); return { data, loading, error, setData } }
function Info({ label, value }) { return <div className="info-item"><span>{label}</span><strong>{value || 'Not available'}</strong></div> }
function label(value) { return value.replace(/([A-Z])/g, ' $1').replace(/^./, (char) => char.toUpperCase()).replace('Pin', 'PIN') }
function priceNumber(value) { const digits = String(value || '').replace(/[^0-9.]/g, ''); return digits ? Number(digits) : 0 }
function formatMoney(value) { return `Rs ${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}` }
function localQr(value) {
  const text = String(value || 'EventSphere'); let hash = 0
  for (let index = 0; index < text.length; index += 1) hash = ((hash << 5) - hash + text.charCodeAt(index)) | 0
  const cells = Array.from({ length: 21 }, (_, y) => Array.from({ length: 21 }, (_, x) => {
    const marker = (x < 7 && y < 7) || (x > 13 && y < 7) || (x < 7 && y > 13)
    return marker || Math.abs(Math.sin((x + 1) * (y + 1) * (hash || 7))) > .48
  }))
  const rects = cells.flatMap((row, y) => row.map((on, x) => on ? `<rect x="${x * 8}" y="${y * 8}" width="8" height="8"/>` : '')).join('')
  return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="168" height="168" viewBox="0 0 168 168"><rect width="168" height="168" fill="white"/><g fill="#111827">${rects}</g></svg>`)}`
}

function Bookings({ bookings, token, setBookings, refresh, setMessage }) { return <section className="section-block auth-card"><p className="eyebrow">User dashboard</p><h2>Booking history</h2>{bookings.length ? bookings.map((booking) => <div className="booking-item" key={booking.id}><span>{booking.confirmationCode} - {booking.quantity} ticket(s) - {booking.status}</span>{booking.status !== 'CANCELLED' && <button className="ghost-btn" onClick={async () => { try { const updated = await cancelBooking(token, booking.id); setBookings((items) => items.map((item) => item.id === updated.id ? updated : item)); refresh(); setMessage('Booking cancelled.'); } catch (error) { setMessage(error.message) } }}>Cancel</button>}</div>) : <p>No bookings yet.</p>}</section> }

function OrganizerDashboard({ session, categories, onExit }) {
  const [tab, setTab] = useState('overview'); const [events, setEvents] = useState([]); const [analytics, setAnalytics] = useState(null); const [editing, setEditing] = useState(null); const [attendees, setAttendees] = useState([]); const [message, setMessage] = useState('')
  const load = () => Promise.all([fetchOrganizerEvents(session.token), fetchOrganizerAnalytics(session.token)]).then(([myEvents, stats]) => { setEvents(myEvents); setAnalytics(stats) }).catch((e) => setMessage(e.message));
  useEffect(() => { load() }, [])
  const save = async (event, values) => { event.preventDefault(); const data = { ...values, seatsLeft: Number(values.seatsLeft) }; try { if (data.id) await updateEvent(session.token, data.id, data); else await createEvent(session.token, data); setEditing(null); load(); setMessage('Event saved.'); } catch (e) { setMessage(e.message) } }
  return <DashboardShell title="Organizer Dashboard" tab={tab} setTab={setTab} tabs={['overview', 'events', 'create', 'attendees', 'reports']} onExit={onExit}><p className="status-message">{message}</p>{tab === 'overview' && <Stats stats={analytics} labels={{ events: 'My events', published: 'Published', registrations: 'Registrations', remainingSeats: 'Seats remaining' }}/>} {tab === 'events' && <EventManager events={events} onEdit={(event) => { setEditing(event); setTab('create') }} onDelete={async (id) => { await deleteEvent(session.token, id); load() }}/>} {tab === 'create' && <EventForm key={editing?.id || 'new'} event={editing || blankEvent} categories={categories} onSave={save} onCancel={() => { setEditing(null); setTab('events') }}/>} {tab === 'attendees' && <AttendeeManager events={events} token={session.token} attendees={attendees} setAttendees={setAttendees}/>} {tab === 'reports' && <section className="auth-card"><h2>Organizer report</h2><p>Download-ready summary: {analytics?.registrations || 0} confirmed registrations across {analytics?.events || 0} events.</p></section>}</DashboardShell>
}

function AdminDashboard({ session, categories, setCategories, onExit }) {
  const [tab, setTab] = useState('overview'); const [users, setUsers] = useState([]); const [stats, setStats] = useState(null); const [reports, setReports] = useState(null); const [events, setEvents] = useState([]); const [newCategory, setNewCategory] = useState(''); const [message, setMessage] = useState('')
  const load = () => Promise.all([fetchAdminUsers(session.token), fetchAdminStatistics(session.token), fetchAdminReports(session.token), fetchEvents()]).then(([u,s,r,e]) => { setUsers(u); setStats(s); setReports(r); setEvents(e) }).catch((e) => setMessage(e.message));
  useEffect(() => { load() }, [])
  return <DashboardShell title="Admin Dashboard" tab={tab} setTab={setTab} tabs={['overview', 'users', 'organizers', 'events', 'categories', 'reports']} onExit={onExit}><p className="status-message">{message}</p>{tab === 'overview' && <Stats stats={stats} labels={{ users: 'Users', organizers: 'Organizers', events: 'Events', bookings: 'Bookings', availableSeats: 'Open seats' }}/>} {(tab === 'users' || tab === 'organizers') && <UserManager users={users.filter((user) => tab === 'users' || user.role === 'ORGANIZER')} token={session.token} onChange={load}/>} {tab === 'events' && <EventManager events={events} onDelete={async (id) => { await deleteEvent(session.token, id); load() }}/>} {tab === 'categories' && <section className="auth-card"><h2>Manage categories</h2><form className="inline-form" onSubmit={async (e) => { e.preventDefault(); try { const category = await createCategory(session.token, newCategory); setCategories((items) => [...items, category]); setNewCategory(''); } catch (error) { setMessage(error.message) } }}><input value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder="Category name" required/><button className="primary-btn">Add</button></form>{categories.map((category) => <div className="booking-item" key={category.id}><span>{category.name}</span><button className="ghost-btn" onClick={async () => { await deleteCategory(session.token, category.id); setCategories((items) => items.filter((item) => item.id !== category.id)) }}>Delete</button></div>)}</section>} {tab === 'reports' && <section className="auth-card"><h2>Platform reports</h2><p>{reports?.events?.length || 0} events - {reports?.recentBookings?.length || 0} recent bookings</p>{reports?.recentBookings?.map((booking) => <div className="booking-item" key={booking.id}><span>{booking.confirmationCode} - {booking.status} - {booking.quantity} ticket(s)</span></div>)}</section>}</DashboardShell>
}

function DashboardShell({ title, tabs, tab, setTab, onExit, children }) { return <div className="app-shell"><header className="topbar"><strong className="brand">{title}</strong><button className="ghost-btn" onClick={onExit}>Back to events</button></header><main><div className="dashboard-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'primary-btn' : 'ghost-btn'} onClick={() => setTab(item)}>{item}</button>)}</div>{children}</main></div> }
function Stats({ stats, labels }) { return <section className="stats-grid">{stats && Object.entries(labels).map(([key, label]) => <div className="hero-stat" key={key}><strong>{stats[key] ?? 0}</strong><span>{label}</span></div>)}</section> }
function EventManager({ events, onEdit, onDelete }) { return <section className="auth-card"><h2>Manage events</h2>{events.map((event) => <div className="booking-item" key={event.id}><span>{event.title} - {event.status} - {event.seatsLeft} seats</span><div>{onEdit && <button className="ghost-btn" onClick={() => onEdit(event)}>Edit</button>} <button className="ghost-btn" onClick={() => onDelete(event.id)}>Delete</button></div></div>)}{!events.length && <p>No events yet.</p>}</section> }
function EventForm({ event, categories, onSave, onCancel }) { const [data, setData] = useState(event); const field = (name, type = 'text') => <input required={name !== 'imageUrl'} type={type} value={data[name] ?? ''} onChange={(e) => setData({ ...data, [name]: e.target.value })} placeholder={name}/>; return <section className="auth-card"><h2>{data.id ? 'Edit event' : 'Create event'}</h2><form className="auth-form" onSubmit={(e) => onSave(e, data)}>{field('title')}<textarea required value={data.description} onChange={(e) => setData({ ...data, description: e.target.value })} placeholder="Description"/>{field('organizer')}<select value={data.category} onChange={(e) => setData({ ...data, category: e.target.value })}>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select>{field('location')}{field('startDate', 'date')}{field('startTime', 'time')}{field('price')}{field('seatsLeft', 'number')}{field('imageUrl')}<select value={data.status} onChange={(e) => setData({ ...data, status: e.target.value })}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select><button className="primary-btn">Save event</button><button type="button" className="ghost-btn" onClick={onCancel}>Cancel</button></form></section> }
function AttendeeManager({ events, token, attendees, setAttendees }) { const [selected, setSelected] = useState(null); return <section className="auth-card"><h2>Attendee list</h2><select value={selected || ''} onChange={async (e) => { const id = e.target.value; setSelected(id); setAttendees(id ? await fetchAttendees(token, id) : []) }}><option value="">Select an event</option>{events.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select>{attendees.map((entry) => <div className="booking-item" key={entry.booking.id}><span>{entry.attendee?.name || entry.booking.userEmail} - {entry.attendee?.email || ''} - {entry.booking.quantity} ticket(s) - {entry.booking.status}</span></div>)}</section> }
function UserManager({ users, token, onChange }) { return <section className="auth-card"><h2>Manage accounts</h2>{users.map((user) => <div className="booking-item" key={user.id}><span>{user.name} - {user.email} - {user.role} - {user.enabled ? 'Active' : 'Disabled'}</span><div><select value={user.role} onChange={async (e) => { await updateAdminUser(token, user.id, { role: e.target.value }); onChange() }}><option>USER</option><option>ORGANIZER</option><option>ADMIN</option></select><button className="ghost-btn" onClick={async () => { await updateAdminUser(token, user.id, { enabled: !user.enabled }); onChange() }}>{user.enabled ? 'Disable' : 'Enable'}</button></div></div>)}</section> }
function HomeExtras() {
  return <>
    <section className="discovery-section" aria-labelledby="cities-heading"><div className="section-heading"><div><p className="eyebrow">Popular cities</p><h2 id="cities-heading">Experiences near you</h2></div></div><div className="city-grid">{['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad', 'Pune', 'Chennai'].map((city) => <button className="city-card" key={city}>{city}<span>Explore events</span></button>)}</div></section>
    <section className="discovery-section split-section"><div><p className="eyebrow">Why EventSphere</p><h2>From plans to packed houses.</h2><p>Discover inspiring local experiences, reserve your spot in seconds, and keep every ticket in one place.</p></div><div className="trust-grid"><div><strong>Simple booking</strong><span>Clear prices and instant confirmations.</span></div><div><strong>Made for India</strong><span>Local events, cities, and communities.</span></div><div><strong>For every host</strong><span>Tools to create and manage memorable events.</span></div></div></section>
    <section className="testimonial"><p>EventSphere made it effortless to find a great workshop for our whole team.</p><span> </span></section>
  </>
}

export default App
