import { useEffect, useState } from 'react'
import './App.css'
import {
  cancelBooking, createBooking, createCategory, createEvent, deleteCategory, deleteEvent, fetchAdminReports,
  fetchAdminStatistics, fetchAdminUsers, fetchAttendees, fetchBookings, fetchCategories, fetchEvents,
  fetchOrganizerAnalytics, fetchOrganizerEvents, loginUser, registerUser, updateAdminUser, updateEvent,
} from './api'

const blankEvent = { title: '', description: '', category: 'Technology', location: '', organizer: '', imageUrl: '', price: 'Free', seatsLeft: 50, startDate: '', startTime: '18:00', status: 'DRAFT' }

function App() {
  const [events, setEvents] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState(''); const [authMode, setAuthMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '', phone: '' })
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('eventsphere-session') || 'null')); const [search, setSearch] = useState(''); const [selectedEvent, setSelectedEvent] = useState(null); const [quantity, setQuantity] = useState(1); const [bookings, setBookings] = useState([]); const [screen, setScreen] = useState('home')
  const loadCatalog = () => Promise.all([fetchEvents(), fetchCategories()]).then(([eventData, categoryData]) => { setEvents(eventData); setCategories(categoryData); setLoading(false) }).catch(() => { setMessage('Unable to reach the API right now.'); setLoading(false) })
  useEffect(() => { loadCatalog() }, [])
  useEffect(() => { if (session?.role === 'USER') fetchBookings(session.token).then(setBookings).catch((error) => setMessage(error.message)) }, [session])
  const signOut = () => { localStorage.removeItem('eventsphere-session'); setSession(null); setBookings([]); setScreen('home'); setMessage('Signed out.') }
  const handleSubmit = async (event) => { event.preventDefault(); try { const result = authMode === 'login' ? await loginUser(form.email, form.password) : await registerUser(form); localStorage.setItem('eventsphere-session', JSON.stringify(result)); setSession(result); setScreen(result.role === 'USER' ? 'home' : 'dashboard'); setMessage('Signed in successfully.'); } catch (error) { setMessage(error.message) } }
  const bookEvent = async () => { if (!session) { setAuthMode('login'); setMessage('Please sign in to book tickets.'); setScreen('auth'); return } if (session.role !== 'USER') return setMessage('Only user accounts can book tickets.'); try { const booking = await createBooking(session.token, selectedEvent.id, Number(quantity)); setBookings((current) => [booking, ...current]); setSelectedEvent(null); setMessage(`Booking confirmed. Ticket code: ${booking.confirmationCode}`); loadCatalog() } catch (error) { setMessage(error.message) } }
  const visibleEvents = events.filter((event) => `${event.title} ${event.category} ${event.location} ${event.organizer}`.toLowerCase().includes(search.toLowerCase()))
  if (session?.role === 'ORGANIZER' && screen === 'dashboard') return <OrganizerDashboard session={session} categories={categories} onExit={() => setScreen('home')} />
  if (session?.role === 'ADMIN' && screen === 'dashboard') return <AdminDashboard session={session} categories={categories} setCategories={setCategories} onExit={() => setScreen('home')} />
  return <div className="app-shell"><header className="topbar"><button className="brand link-button" onClick={() => setScreen('home')}>EventSphere</button><nav className="nav-links"><button onClick={() => setScreen('home')}>Events</button><button onClick={() => setScreen('auth')}>{session ? 'Account' : 'Login'}</button>{session && session.role !== 'USER' && <button onClick={() => setScreen('dashboard')}>Dashboard</button>}</nav><div className="topbar-actions">{session ? <button className="ghost-btn" onClick={signOut}>Logout</button> : <button className="primary-btn" onClick={() => { setAuthMode('register'); setScreen('auth') }}>Register</button>}</div></header><main>
    {screen === 'home' && <><section className="hero-card"><div className="hero-copy"><p className="eyebrow">Discover and manage events</p><h1>Find your next unforgettable experience.</h1><p className="hero-text">Browse events, reserve tickets, and manage every stage of your event.</p><div className="hero-actions"><input className="search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, category, location, organizer" /></div></div><div className="hero-panel"><div className="hero-stat"><strong>{events.length}</strong><span>Events available</span></div><div className="hero-stat"><strong>{categories.length}</strong><span>Categories</span></div></div></section>
      <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Browse by category</p><h2>Explore events</h2></div></div><div className="chip-row">{categories.map((category) => <button className="chip" key={category.id} onClick={() => setSearch(category.name)}>{category.name}</button>)}<button className="chip" onClick={() => setSearch('')}>All</button></div><div className="card-grid">{loading ? <p>Loading events...</p> : visibleEvents.map((event) => <article className="event-card" key={event.id}><img src={event.imageUrl || 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80'} alt=""/><div className="event-body"><div className="event-meta">{event.category} · {event.startDate}</div><h3>{event.title}</h3><p>{event.location} · {event.organizer}</p><div className="event-footer"><span>{event.price}</span><span>{event.seatsLeft} left</span></div><button className="primary-btn" onClick={() => { setSelectedEvent(event); setQuantity(1) }}>View details</button></div></article>)}</div></section>
      <HomeExtras />
      {selectedEvent && <EventDetail event={selectedEvent} quantity={quantity} setQuantity={setQuantity} onBook={bookEvent} onClose={() => setSelectedEvent(null)} />}
      {session?.role === 'USER' && <Bookings bookings={bookings} token={session.token} setBookings={setBookings} refresh={loadCatalog} setMessage={setMessage} />}</>}
    {screen === 'auth' && <section className="section-block auth-card"><div className="section-heading"><div><p className="eyebrow">Account</p><h2>{authMode === 'login' ? 'Login to EventSphere' : 'Create your account'}</h2></div><div className="toggle-row"><button className="ghost-btn" onClick={() => setAuthMode('login')}>Login</button><button className="primary-btn" onClick={() => setAuthMode('register')}>Register</button></div></div><form onSubmit={handleSubmit} className="auth-form">{authMode === 'register' && <><input required placeholder="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/><input placeholder="Phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })}/></>}<input required type="email" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/><input required minLength="8" type="password" placeholder="Password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })}/><button className="primary-btn">{authMode === 'login' ? 'Sign in' : 'Create account'}</button></form></section>}
    {message && <p className="status-message">{message}</p>}
  </main></div>
}

function EventDetail({ event, quantity, setQuantity, onBook, onClose }) { return <section className="section-block auth-card"><div className="section-heading"><div><p className="eyebrow">Event details</p><h2>{event.title}</h2></div><button className="ghost-btn" onClick={onClose}>Close</button></div><p>{event.description}</p><p>{event.startDate} at {event.startTime} · {event.location} · Hosted by {event.organizer}</p><p>{event.price} · {event.seatsLeft} seats remain</p><div className="booking-row"><input type="number" min="1" max={event.seatsLeft} value={quantity} onChange={(e) => setQuantity(e.target.value)}/><button className="primary-btn" disabled={!event.seatsLeft} onClick={onBook}>Book ticket</button></div></section> }
function Bookings({ bookings, token, setBookings, refresh, setMessage }) { return <section className="section-block auth-card"><p className="eyebrow">User dashboard</p><h2>Booking history</h2>{bookings.length ? bookings.map((booking) => <div className="booking-item" key={booking.id}><span>{booking.confirmationCode} · {booking.quantity} ticket(s) · {booking.status}</span>{booking.status === 'CONFIRMED' && <button className="ghost-btn" onClick={async () => { try { const updated = await cancelBooking(token, booking.id); setBookings((items) => items.map((item) => item.id === updated.id ? updated : item)); refresh(); setMessage('Booking cancelled.'); } catch (error) { setMessage(error.message) } }}>Cancel</button>}</div>) : <p>No bookings yet.</p>}</section> }

function OrganizerDashboard({ session, categories, onExit }) {
  const [tab, setTab] = useState('overview'); const [events, setEvents] = useState([]); const [analytics, setAnalytics] = useState(null); const [editing, setEditing] = useState(null); const [attendees, setAttendees] = useState([]); const [message, setMessage] = useState('')
  const load = () => Promise.all([fetchOrganizerEvents(session.token), fetchOrganizerAnalytics(session.token)]).then(([myEvents, stats]) => { setEvents(myEvents); setAnalytics(stats) }).catch((e) => setMessage(e.message)); // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load() }, [])
  const save = async (event, values) => { event.preventDefault(); const data = { ...values, seatsLeft: Number(values.seatsLeft) }; try { if (data.id) await updateEvent(session.token, data.id, data); else await createEvent(session.token, data); setEditing(null); load(); setMessage('Event saved.'); } catch (e) { setMessage(e.message) } }
  return <DashboardShell title="Organizer Dashboard" tab={tab} setTab={setTab} tabs={['overview', 'events', 'create', 'attendees', 'reports']} onExit={onExit}><p className="status-message">{message}</p>{tab === 'overview' && <Stats stats={analytics} labels={{ events: 'My events', published: 'Published', registrations: 'Registrations', remainingSeats: 'Seats remaining' }}/>} {tab === 'events' && <EventManager events={events} onEdit={(event) => { setEditing(event); setTab('create') }} onDelete={async (id) => { await deleteEvent(session.token, id); load() }}/>} {tab === 'create' && <EventForm key={editing?.id || 'new'} event={editing || blankEvent} categories={categories} onSave={save} onCancel={() => { setEditing(null); setTab('events') }}/>} {tab === 'attendees' && <AttendeeManager events={events} token={session.token} attendees={attendees} setAttendees={setAttendees}/>} {tab === 'reports' && <section className="auth-card"><h2>Organizer report</h2><p>Download-ready summary: {analytics?.registrations || 0} confirmed registrations across {analytics?.events || 0} events.</p></section>}</DashboardShell>
}

function AdminDashboard({ session, categories, setCategories, onExit }) {
  const [tab, setTab] = useState('overview'); const [users, setUsers] = useState([]); const [stats, setStats] = useState(null); const [reports, setReports] = useState(null); const [events, setEvents] = useState([]); const [newCategory, setNewCategory] = useState(''); const [message, setMessage] = useState('')
  const load = () => Promise.all([fetchAdminUsers(session.token), fetchAdminStatistics(session.token), fetchAdminReports(session.token), fetchEvents()]).then(([u,s,r,e]) => { setUsers(u); setStats(s); setReports(r); setEvents(e) }).catch((e) => setMessage(e.message)); // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load() }, [])
  return <DashboardShell title="Admin Dashboard" tab={tab} setTab={setTab} tabs={['overview', 'users', 'organizers', 'events', 'categories', 'reports']} onExit={onExit}><p className="status-message">{message}</p>{tab === 'overview' && <Stats stats={stats} labels={{ users: 'Users', organizers: 'Organizers', events: 'Events', bookings: 'Bookings', availableSeats: 'Open seats' }}/>} {(tab === 'users' || tab === 'organizers') && <UserManager users={users.filter((user) => tab === 'users' || user.role === 'ORGANIZER')} token={session.token} onChange={load}/>} {tab === 'events' && <EventManager events={events} onDelete={async (id) => { await deleteEvent(session.token, id); load() }}/>} {tab === 'categories' && <section className="auth-card"><h2>Manage categories</h2><form className="inline-form" onSubmit={async (e) => { e.preventDefault(); try { const category = await createCategory(session.token, newCategory); setCategories((items) => [...items, category]); setNewCategory(''); } catch (error) { setMessage(error.message) } }}><input value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder="Category name" required/><button className="primary-btn">Add</button></form>{categories.map((category) => <div className="booking-item" key={category.id}><span>{category.name}</span><button className="ghost-btn" onClick={async () => { await deleteCategory(session.token, category.id); setCategories((items) => items.filter((item) => item.id !== category.id)) }}>Delete</button></div>)}</section>} {tab === 'reports' && <section className="auth-card"><h2>Platform reports</h2><p>{reports?.events?.length || 0} events · {reports?.recentBookings?.length || 0} recent bookings</p>{reports?.recentBookings?.map((booking) => <div className="booking-item" key={booking.id}><span>{booking.confirmationCode} · {booking.status} · {booking.quantity} ticket(s)</span></div>)}</section>}</DashboardShell>
}

function DashboardShell({ title, tabs, tab, setTab, onExit, children }) { return <div className="app-shell"><header className="topbar"><strong className="brand">{title}</strong><button className="ghost-btn" onClick={onExit}>Back to events</button></header><main><div className="dashboard-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'primary-btn' : 'ghost-btn'} onClick={() => setTab(item)}>{item}</button>)}</div>{children}</main></div> }
function Stats({ stats, labels }) { return <section className="stats-grid">{stats && Object.entries(labels).map(([key, label]) => <div className="hero-stat" key={key}><strong>{stats[key] ?? 0}</strong><span>{label}</span></div>)}</section> }
function EventManager({ events, onEdit, onDelete }) { return <section className="auth-card"><h2>Manage events</h2>{events.map((event) => <div className="booking-item" key={event.id}><span>{event.title} · {event.status} · {event.seatsLeft} seats</span><div>{onEdit && <button className="ghost-btn" onClick={() => onEdit(event)}>Edit</button>} <button className="ghost-btn" onClick={() => onDelete(event.id)}>Delete</button></div></div>)}{!events.length && <p>No events yet.</p>}</section> }
function EventForm({ event, categories, onSave, onCancel }) { const [data, setData] = useState(event); const field = (name, type = 'text') => <input required={name !== 'imageUrl'} type={type} value={data[name] ?? ''} onChange={(e) => setData({ ...data, [name]: e.target.value })} placeholder={name}/>; return <section className="auth-card"><h2>{data.id ? 'Edit event' : 'Create event'}</h2><form className="auth-form" onSubmit={(e) => onSave(e, data)}>{field('title')}<textarea required value={data.description} onChange={(e) => setData({ ...data, description: e.target.value })} placeholder="Description"/>{field('organizer')}<select value={data.category} onChange={(e) => setData({ ...data, category: e.target.value })}>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select>{field('location')}{field('startDate', 'date')}{field('startTime', 'time')}{field('price')}{field('seatsLeft', 'number')}{field('imageUrl')}<select value={data.status} onChange={(e) => setData({ ...data, status: e.target.value })}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select><button className="primary-btn">Save event</button><button type="button" className="ghost-btn" onClick={onCancel}>Cancel</button></form></section> }
function AttendeeManager({ events, token, attendees, setAttendees }) { const [selected, setSelected] = useState(null); return <section className="auth-card"><h2>Attendee list</h2><select value={selected || ''} onChange={async (e) => { const id = e.target.value; setSelected(id); setAttendees(id ? await fetchAttendees(token, id) : []) }}><option value="">Select an event</option>{events.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select>{attendees.map((entry) => <div className="booking-item" key={entry.booking.id}><span>{entry.attendee?.name || entry.booking.userEmail} · {entry.attendee?.email || ''} · {entry.booking.quantity} ticket(s) · {entry.booking.status}</span></div>)}</section> }
function UserManager({ users, token, onChange }) { return <section className="auth-card"><h2>Manage accounts</h2>{users.map((user) => <div className="booking-item" key={user.id}><span>{user.name} · {user.email} · {user.role} · {user.enabled ? 'Active' : 'Disabled'}</span><div><select value={user.role} onChange={async (e) => { await updateAdminUser(token, user.id, { role: e.target.value }); onChange() }}><option>USER</option><option>ORGANIZER</option><option>ADMIN</option></select><button className="ghost-btn" onClick={async () => { await updateAdminUser(token, user.id, { enabled: !user.enabled }); onChange() }}>{user.enabled ? 'Disable' : 'Enable'}</button></div></div>)}</section> }
function HomeExtras() {
  return <>
    <section className="discovery-section" aria-labelledby="cities-heading"><div className="section-heading"><div><p className="eyebrow">Popular cities</p><h2 id="cities-heading">Experiences near you</h2></div></div><div className="city-grid">{['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad', 'Pune', 'Chennai'].map((city) => <button className="city-card" key={city}>{city}<span>Explore events →</span></button>)}</div></section>
    <section className="discovery-section split-section"><div><p className="eyebrow">Why EventSphere</p><h2>From plans to packed houses.</h2><p>Discover inspiring local experiences, reserve your spot in seconds, and keep every ticket in one place.</p></div><div className="trust-grid"><div><strong>Simple booking</strong><span>Clear prices and instant confirmations.</span></div><div><strong>Made for India</strong><span>Local events, cities, and communities.</span></div><div><strong>For every host</strong><span>Tools to create and manage memorable events.</span></div></div></section>
    <section className="testimonial"><p>“EventSphere made it effortless to find a great workshop for our whole team.”</p><span>— Ananya S., Bengaluru</span></section>
  </>
}

export default App
